# Used for developing overseerrPlus
version: '3'
services:
  overseerr:
    build:
      context: .
      dockerfile: Dockerfile.plus.local
      # container_name: overseerrPlus
    image: overseerrplus:dev
    env_file:
      - .dev.plus.env
    ports:
      - 5055:5055
    volumes:
      - .:/app:rw
      - /app/node_modules
      - /app/.next
      - ./config:/app/config
