# Used for developing overseerrPlus
version: '3'
services:
  overseerr:
    build:
      context: .
      dockerfile: Dockerfile.plus.local
    ports:
      - 5055:5055
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
      - /app/.next
      - ./config:/app/config
