FROM sctx/overseerr:latest

# Install git
RUN apk add --no-cache git

RUN git clone -–depth 1 -b plus/production https://github.com/JamesWRC/overseerrPlus overseerrPlusTemp
RUN ls 
RUN pwd

RUN ls overseerrPlusTemp


RUN cp -R overseerrPlusTemp/* .
RUN rm -rf overseerrPlusTemp

RUN yarn install
RUN yarn build