# Used for overseerrPlus production
version: '3'
services:
  overseerr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: overseerrPlus
    image: overseerrplus:latest
    env_file:
      - .prod.plus.env
    ports:
      - 5055:5055
    volumes:
      - ./prodConfig:/app/config
