# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "plus/main" branch
  push:
    branches: [ "plus/main" ]
  pull_request:
    branches: [ "plus/main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: 'old var'
        run: echo CURR_PLUS_COMMIT_TAG=$(curl -s "https://api.github.com/repos/JamesWRC/overseerrPlus/releases" | python3 -c 'import json,sys;releases=json.load(sys.stdin); print([rel.get("tag_name") for rel in releases if rel.get("target_commitish") == "plus/main" ][0].upper().replace("V","") ') >> $GITHUB_ENV
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.CURR_PLUS_COMMIT_TAG }}
          version-fragment: 'feature'
      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}
  # will print 2.12.0
      - name: Set env
        run: |
          echo "PLUS_ENV=$(echo $GITHUB_PLUS_ENV | cut -c 1-6)" >> $GITHUB_ENV
          echo "PLUS_COMMIT_TAG=$(echo $GITHUB_PLUS_COMMIT_TAG | cut -c 1-6)" >> $GITHUB_ENV
          echo "PLUS_GIT_BRANCH=$(echo $GITHUB_PLUS_GIT_BRANCH | cut -c 1-6)" >> $GITHUB_ENV
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
